### PR TITLE
Review and critique

### PR DESCRIPTION
**Pull request by plitter**
Looking forward to the critique.

### CODE REVIEW

**Comment by romainl** [comment]
This is promising.

I like the fact that it's written in the context of other vimways article.

You use "obvious*" a few times but I don't think there's anything obvious about what you consider obvious, here. You don't mention `?` anywhere and I think it should be. You quickly mention `n` and `N` in the same sentence but they should probably be explained on their own, especially their directionality.

Could you take a look at how past articles are formatted?

**Comment by plitter** [comment]
Yes, I also realize I didn't mention f or F as well. I'm going to write those in.
I didn't think about the diff when I was writing... how would you want me to do it? vim recognized the .md format and magically fixed for me.

**Comment by romainl** [comment]
OK, I merged your post, I will go through it, format it cleanly, and come back to you.

**Comment by romainl** [comment]
@plitter I'm not finished yet, but could you take a look at what I did to your text?

https://github.com/vim-advent-calendar/vimways.org/commit/15d9d0e0aa55b19f6fabcc8bf9ab40a4b2ffbd36#diff-5b3c45a28aa1bfead8e724967c248633

**Comment by romainl** [comment]
@plitter I think I'm done with my editorializing. Could you check it out and tell me if you are OK with what I did?

**Comment by plitter** [comment]
Yeah, it looks good :+1:  I did get to look a bit into creating asciinema, but there were some things I didn't like about it. F.ex. you don't see operator keys being typed. So I checked out ffmpeg and screenkey. I think I got the example with String result1... to slightly less than 500kb with ffmpeg and screenkey (OOB, could probably be made even lower if I processed the movie afterwards). Is that something to we could use next time? Happy christmas :)

**Comment by romainl** [comment]
Published.

**Pull request merged**
