### PR TITLE
dylnmc article

### PR DESCRIPTION
**Pull request by dylnmc**
sorry it's not on something more interesting

### CODE REVIEW

**Comment by oblitum** [comment]
*you* are interesting @dylnmc.

**Comment by dylnmc** [comment]
@oblitum you know somethin'? I *just* got that reference. Good one. See you around, kid. Take care of yourself.

**Comment by oblitum** [comment]
@dylnmc ▯

**Comment by kutsan** [comment]
> `" magic is needed for this (/\v doesn't seem work)`

It works actually, don't know why you said that.

https://github.com/kutsan/dotfiles/blob/1373c7149baa7a7e3f619f0958571de4b37681b4/.vim/autoload/kutsan/mappings/motion/indent.vim

and I think we shouldn't use two separate functions to this to work.

And thanks for the function, I didn't know about `/\%v` before.

**Pull request merged**
