### PR TITLE
Add article on Vim's default colors

### PR DESCRIPTION
**Pull request by george-b**
Initial commit of article.

Details what I learned from creating [this](https://github.com/george-b/zenchrome) colorscheme rather than the colorscheme itself. I've been purposly light on details around the implementation by just giving links for two reasons.

1. The code that is linked to is likey to change between now and when this is published.
2. I think it detracts focus from the description of what *Vim* is doing to what *I* am doing. 

Is this sort of content of interest?

Also is there a preference for the license? I don't think there was one last year.

### CODE REVIEW

**Comment by romainl** [comment]
I plan to write a two-parts post on colorscheme design and implementation for this year's vimways. I think this post and my second part will complement each other well.

FWIW, you might be interested in these two files:

* https://github.com/vim/vim/blob/c799fe206e61f2e2c1231bc46cbe4bb354f3da69/src/syntax.c#L6815-L7150
* https://github.com/vim/vim/blob/c799fe206e61f2e2c1231bc46cbe4bb354f3da69/runtime/syntax/syncolor.vim

**Comment by george-b** [comment]
Thanks for the links, I'll flesh out my comment of "hardcoded" hand wave to better reflect those.

**Comment by george-b** [comment]
I think I'm pretty much done with this. Let me know if it looks good to you and I can squash the commits.

**Comment by romainl** [comment]
@george-b I've spotted a couple of spelling/grammar issues. Will come back to it this week-end and double check the technical aspects. Thank you for this!

**Pull request merged**
