### PR TITLE
Add article about vim and cwd

### PR DESCRIPTION
**Pull request by dmerejkowsky**
Initially published on my blog

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Note: the vimscript at the end only works in Neovim. If you insist, I can try and make it work with vaniall vim too ...

**Comment by romainl** [comment]
> Note: the vimscript at the end only works in Neovim. If you insist, I can try and make it work with vaniall vim too ...

Yes, Dimitri, that would be cool.

**Comment by dmerejkowsky** [comment]
I can't manage to make it work :/ The event name is different on vim, but the call back is always called with an empty path. Not sure why

**Comment by george-b** [comment]
`tcd` does not exist in Vim, it is Neovim specific.

https://github.com/neovim/neovim/blob/db436d5277a605606ac92cfabe9e58d86f48f64e/runtime/doc/vim_diff.txt#L148

https://github.com/neovim/neovim/commit/ec71d87b8140ae097158f7e219b26701aed8158e

**Comment by romainl** [comment]
What is the goal of that autocommand, exactly? What is the expected behaviour when doing:

* `:tabnew`?
* `:tabedit foo`?
* `<C-w>f`?

**Comment by dmerejkowsky** [comment]
> `tcd` does not exist in Vim, it is Neovim specific.

It *used* to be neovim-specific, but it has been added to vim in this commit: https://github.com/vim/vim/commit/00aa069db8132851a91cfc5ca7f58ef945c75c73

> Nothing is matched with the Tab* event because tab pages don't have names or paths associated with them.

Do they? When you do `tabedit foo.c`, the tab name should be `foo.c`, no?

> What is the goal of that autocommand, exactly? 

I type `tabnew path/to/src/foo.c` and I want to:
* create a new tab
* open foo.c in this tab
* call `tcd /path/to/src`

> What is the expected behavior when doing:

Not sure. Back when I was using vim, I only ever used `:tabnew` :P

**Comment by george-b** [comment]
> It used to be neovim-specific, but it has been added to vim in this commit: vim/vim@00aa069

Ah thanks, it wasn't in my Vim so I just checked Neovim's list of differences and didn't consult Vim's upstream.

**Comment by romainl** [comment]
> > Nothing is matched with the Tab* event because tab pages don't have names or paths associated with them.
> 
> Do they? When you do `tabedit foo.c`, the tab name should be `foo.c`, no?

No, tab pages don't have names. You would need `WinEnter`, triggered before `TabNew`, to get `foo.c`.

> > What is the goal of that autocommand, exactly?

> I type `tabnew path/to/src/foo.c` and I want to:
> 
> * create a new tab
> * open foo.c in this tab
> * call `tcd /path/to/src`
> 
> > What is the expected behavior when doing:
> 
> Not sure. Back when I was using vim, I only ever used `:tabnew` :P

This is important, actually. It should be possible to rewrite the function using the right events but it will have to be more complicated.

**Comment by dmerejkowsky** [comment]
> This is important, actually. It should be possible to rewrite the function using the right events but it will have to be more complicated.

Yup. Maybe we can just remove the last paragraph ?

**Comment by romainl** [comment]
> > This is important, actually. It should be possible to rewrite the function using the right events but it will have to be more complicated.
> 
> Yup. Maybe we can just remove the last paragraph ?

I have a better idea: turn it into some kind of feature request.

**Comment by dmerejkowsky** [comment]
I've added a small paragraph with what we know. I hope this is enough, because I don't feel like digging through vim's issues and source code for a piece of code I no longer use ...

**Pull request merged**
